# -*- coding: utf-8 -*-
import logging
from odoo import models, api

_logger = logging.getLogger(__name__)

class ResUsers(models.Model):
    _inherit = 'res.users'

    def _send_reset_password_email(self, body=None):
        """
        Override: Log the reset password link to console for local development
        where email service might not be configured.
        """
        # Call super first to preserve original behavior (sending email if possible)
        res = super(ResUsers, self)._send_reset_password_email(body)
        
        for user in self:
            try:
                if not user.signup_token:
                    # Token should have been generated by action_reset_password before calling this
                    continue
                
                db = self.env.cr.dbname
                base_url = user.get_base_url()
                
                # Construct standard auth_signup reset link
                reset_link = f"{base_url}/web/reset_password?token={user.signup_token}&db={db}"
                
                _logger.info("\n" + "="*60)
                _logger.info("LOCAL DEV - PASSWORD RESET LINK for '%s'", user.login)
                _logger.info("-" * 60)
                _logger.info("Reset Link: %s", reset_link)
                _logger.info("="*60 + "\n")
                
            except Exception as e:
                _logger.warning("Failed to log reset password link: %s", str(e))
                
        return res
